
{'date': 'Mon Jul 30 2018 06:50:00.142 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 22
    Game()
NameError: name 'Game' is not defined
'''},
{'date': 'Mon Jul 30 2018 06:58:56.446 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 23
    game()
  module <module> line 22
    fase1.vai()
NameError: name 'fase1' is not defined
'''},
{'date': 'Mon Jul 30 2018 06:59:25.428 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 23
    game()
  module <module> line 22
    linha1.vai()
NameError: name 'linha1' is not defined
'''},
{'date': 'Mon Jul 30 2018 07:00:26.868 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 23
    game()
  module <module> line 22
    faese1.vai()
NameError: name 'faese1' is not defined
'''},
{'date': 'Mon Jul 30 2018 07:00:41.166 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 23
    game()
  module <module> line 22
    fase1.vai()
NameError: name 'fase1' is not defined
'''},
{'date': 'Mon Jul 30 2018 07:25:14.967 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 36
    game()
  module <module> line 34
    self._3d_()
  module <module> line 16
    doc['py3d'].html=''
NameError: name 'doc' is not defined
'''},
{'date': 'Mon Jul 30 2018 07:26:09.480 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 38
    game()
  module <module> line 36
    self._3d_()
  module <module> line 18
    doc['py3d'].html=''
NameError: name 'doc' is not defined
'''},
{'date': 'Mon Jul 30 2018 07:26:28.150 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.main import Cena, Elemento, Texto, STYLE, doc
ImportError: cannot import name 'doc'

ImportError
Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 264
    action()
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.main import Cena, Elemento, Texto, STYLE, doc
'''},
{'date': 'Mon Jul 30 2018 07:49:04.706 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  """
  ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Jul 30 2018 07:49:37.91 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  """def _3d_(self):
  ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Jul 30 2018 07:50:52.626 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 39
    game()
  module <module> line 38
    self._3d_()
AttributeError: 'game' object has no attribute '_3d_'
'''},
{'date': 'Mon Jul 30 2018 08:16:02.562 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    Tabuleiro()
  module <module> line 32
    self.fase1 = Cena(img = FASE1)
NameError: name 'FASE1' is not defined
'''},
{'date': 'Mon Jul 30 2018 08:17:11.583 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    Tabuleiro()
  module <module> line 38
    self.fase1.linhaA1(self.entra) 
AttributeError: 'Cena' object has no attribute 'linhaA1'
'''},
{'date': 'Mon Jul 30 2018 08:26:11.818 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 67
  self.tabela_fase1 = tabelafase1 = Cena(img=FUNDO)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 08:30:34.76 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 104
  for nome in self.tabuleiro["esquerda"]:
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 08:31:19.45 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 112
    Tabuleiro()
  module <module> line 109
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 08:37:41.368 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 114
    Tabuleiro()
  module <module> line 111
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 08:37:58.15 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 114
    Tabuleiro()
  module <module> line 111
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 08:45:43.109 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 112
    Tabuleiro()
  module <module> line 109
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 08:53:02.738 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 112
    Tabuleiro()
  module <module> line 109
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 08:56:04.724 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  def __init__ (self):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 09:00:30.87 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 208
    Tabuleiro()
  module <module> line 109
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 09:04:02.544 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 208
    Tabuleiro()
  module <module> line 109
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 10:27:13.629 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 208
    Tabuleiro()
  module <module> line 106
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 10:30:56.227 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  tabelafase1.vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 10:31:42.26 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  fase1.vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 10:32:29.14 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  self.fase1.vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 10:34:20.526 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  self.fase1.vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 10:34:48.150 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 47
    Tabuleiro()
  module <module> line 43
    self.linhaA1.entra(fase1) 
NameError: name 'fase1' is not defined
'''},
{'date': 'Mon Jul 30 2018 10:38:01.239 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 44
  self._3d_()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 10:38:46.445 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 47
    Tabuleiro()
  module <module> line 44
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 10:39:45.701 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 44
  self._3d_()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 30 2018 10:40:41.165 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 47
    Tabuleiro()
  module <module> line 44
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 10:44:37.736 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 43
    Tabuleiro()
  module <module> line 40
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 10:50:51.543 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 43
    Tabuleiro()
  module <module> line 40
    self._3d_()
  module <module> line 20
    doc['py3d'].html=''
KeyError: py3d
'''},
{'date': 'Mon Jul 30 2018 15:33:39.513 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 79
  for [] : #carta in Pilha_Cartas:
        ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 30 2018 18:22:24.810 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 127
    Tabuleiro()
  module <module> line 41
    self.cria_tabuleiro(col=3, lin=4)
  module <module> line 61
    self.casa["esquerda"][nome] = Casa(self, nome=nome, linha=linha_, coluna=coluna_)
KeyError: esquerda
'''},
{'date': 'Mon Jul 30 2018 18:24:12.966 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 128
    Tabuleiro()
  module <module> line 41
    self.cria_tabuleiro(col=3, lin=4)
  module <module> line 62
    self.casa["esquerda"][nome] = Casa(self, nome=nome, linha=linha_, coluna=coluna_)
  module <module> line 113
    self.tabuleiro.entra(self)
  module <module> line 65
    self.elemento.entra(parte)
AttributeError: 'Tabuleiro' object has no attribute 'elemento'
'''},
{'date': 'Mon Jul 30 2018 18:25:56.67 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Tabuleiro()
  module <module> line 43
    self.cria_tabuleiro(col=3, lin=4)
  module <module> line 60
    self.casa["esquerda"][nome] = Casa(self, nome=nome, linha=linha_, coluna=coluna_)
  module <module> line 111
    self.tabuleiro.entra(self)
  module <module> line 63
    self.elemento.entra(parte)
AttributeError: 'Cena' object has no attribute 'entra'
'''},
{'date': 'Mon Jul 30 2018 18:28:01.946 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Tabuleiro()
  module <module> line 48
    Carta(self, "carta_{}".format(i))
  module <module> line 76
    self.cria_carta(carta_id)
  module <module> line 83
    a_carta_a_ser_empilhada.entra(self.tabuleiro)
  module _spy.vitollino.main line 459
    cena <= self
TypeError: '<=' not supported between instances of 'Tabuleiro' and 'Elemento'
'''},
{'date': 'Mon Jul 30 2018 18:54:16.596 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 54
  INVENTARIO.score(self, casa="9_9", carta="9_9", move="INICIA", ponto=0, valor="N", _level=1):
                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 30 2018 18:55:05.499 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 54
  INVENTARIO.score(casa="9_9", carta="9_9", move="INICIA", ponto=0, valor="N", _level=1):
                                                                                         ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 30 2018 19:12:32.846 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 135
    Tabuleiro()
  module <module> line 43
    self.cria_tabuleiro(col=3, lin=4)
  module <module> line 56
    INVENTARIO.score(casa="centro_9_9", carta="carta_99", move="INICIA", ponto=0, valor="N", _level=1)
NameError: name 'INVENTARIO' is not defined
'''},
{'date': 'Mon Aug 06 2018 11:50:42.124 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 148
    Tabuleiro()
  module <module> line 40
    self.button = Elemento(BUTTON, cena=self.elemento, tit="desiste", style=dict(
NameError: name 'BUTTON' is not defined
'''},
{'date': 'Mon Aug 06 2018 07:34:01.944 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 151
    Jogo()
NameError: name 'Jogo' is not defined
'''},
{'date': 'Mon Aug 06 2018 08:05:55.931 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 81
  self.casa["esquerda"][nome] = Casa(self, nome=nome, linha=linha_, coluna=coluna_, lado)
                                                                                        ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Mon Aug 06 2018 08:59:49.978 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 174
    Jogo()
  module <module> line 169
    proximafase3 = Tabuleiro(**FASE3)
  module <module> line 60
    self._3d_()
  module <module> line 32
    doc['py3d'].html = ''
KeyError: py3d
'''},
{'date': 'Tue Sep 04 2018 21:46:19.181 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 183
    Jogo()
  module <module> line 172
    self.reset()
  module <module> line 175
    self.tabuleiro =  Tabuleiro()
  module <module> line 55
    self.inicia_fase()
  module <module> line 59
    [self.cria_tabuleiro(col=3, lin=self.linha, lado=l) for l in self.lado]
  module <module> line 98
    self.casa["esquerda"][nome] = Casa(self, nome=nome, linha=linha_, coluna=coluna_, lado=lado)
  module <module> line 149
    inicio_x_ = inicio_x + offset[lado]
NameError: name 'offset' is not defined
'''},
{'date': 'Wed Sep 05 2018 07:37:49.675 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 22
  offset = dict(e=0, d=300
                              ^
SyntaxError: invalid syntax
'''},