
{'date': 'Wed Aug 08 2018 08:09:55.755 GMt-1000 (Horário Padrão do Havaí e Ilhas Aleutas) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    jardim1=cena(img="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Butchardgardens.jpg/1200px-Butchardgardens.jpg")
NameError: name 'cena' is not defined
'''},
{'date': 'Mon Sep 24 2018 13:58:57.774 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 211
    Jogo()
  module <module> line 200
    self.reset()
  module <module> line 208
    proximafase3 = Tabuleiro(**FASE3)
TypeError: __init__() got an unexpected keyword argument '_3d'
'''},
{'date': 'Mon Sep 24 2018 13:59:54.218 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 211
    Jogo()
  module <module> line 200
    self.reset()
  module <module> line 208
    proximafase3 = Tabuleiro(**FASE3)
TypeError: __init__() got an unexpected keyword argument '_3d'
'''},
{'date': 'Mon Sep 24 2018 14:00:34.426 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 211
    Jogo()
  module <module> line 200
    self.reset()
  module <module> line 208
    proximafase3 = Tabuleiro(**FASE3)
TypeError: __init__() got an unexpected keyword argument '_3d'
'''},
{'date': 'Mon Sep 24 2018 14:32:08.325 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 217
    Jogo()
  module <module> line 204
    self.reset()
  module <module> line 207
    self.tabuleiro =  Tabuleiro()
  module <module> line 87
    self.inicia_fase()
  module <module> line 91
    [self.cria_tabuleiro(col=3, lin=self.linha, lado=l) for l in self.lado]
  module <module> line 130
    self.casa["esquerda"][nome] = Casa(self, nome=nome, linha=linha_, coluna=coluna_, lado=lado)
  module <module> line 182
    self.nome = nome_elemento = "{}_{}".format(tabuleiro.nome, nome)
AttributeError: 'Tabuleiro' object has no attribute 'nome'
'''},